### ISSUE TITLE
No showing of pubmed records

### ISSUE THREAD

**Issue by whytong** [EricMaeker/dokuwiki-plugin-pubmed#2]
Anyone has an issue with the latest copy? I installed manually and configurated. It seems it is not working. The default Vancouver style showed only ;:, changed the setting to long style, it says "No author listed. . . ;:." Also, the preview does not work.

**Comment by EricMaeker** [comment]
Hello, Can you paste the dokuwiki code of your page here please.

**Comment by EricMaeker** [comment]
Please install and test this new version (sept-2019). Thanks

**Comment by cbso-uc** [comment]
Same problem encountered.
Works when using PMID in your example: {{pubmed>24073682}}, I get "Maher Robert L, Hanlon Joseph, Hajjar Emily R. Clinical consequences of polypharmacy in elderly. Expert Opin Drug Saf. 2014 Jan;13(1):57-65. PMID : 24073682"
If I try to use my own PMID: 30644303 {{pubmed>30644303}}, I end up with "  ;:"
I guess it it the parsing routine that is not working for some different citations.

**Comment by EricMaeker** [comment]
Hello, thanks for reporting. Please try to upgrade the plugin manually,
purge your cache and test
{{pubmed>vancouver:30644303}}

You should read :
Chompoosang T, D'Apolito R, Lacagnina C, Peretti G, Zagra L. Total hip
arthroplasty in rapidly progressive osteoarthritis of the hip: clinical and
radiological outcome of a consecutive series of patients. J Biol Regul
Homeost Agents. 2018 Nov-Dec;32(6 Suppl. 1):201-207

I've just tested on my configuration.
Please confirm this issue.

**Comment by cbso-uc** [comment]
No luck. See screenshot below,

Github shows no new commit since Sep 6 though. Any changes made in the code?

![Capture](https://user-images.githubusercontent.com/57051636/67637235-f8d87500-f89d-11e9-8cec-9fbc7645d812.JPG)

**Comment by EricMaeker** [comment]
Do your website has access to internet ? It seems like the plugins did not
retrieve the citation XML file from NCBI.

Please, follow these steps :
- check internet access
- check rights access (read/write) to media/ncbi_esummary
- remove any file in media/ncbi_esummary *xml *gz
- retry

**Comment by cbso-uc** [comment]
That is not the problem as summaryxml and search works. See screenshots.

![Capture2](https://user-images.githubusercontent.com/57051636/67637796-c16cc700-f8a3-11e9-9a78-f6870f9b63ca.JPG)
![Capture](https://user-images.githubusercontent.com/57051636/67637797-c16cc700-f8a3-11e9-8dc3-3f1bf6eeb4a9.JPG)

**Comment by cbso-uc** [comment]
Checked the media/ncbi_esummary directory. Permission and ownership is fine. No files inside at all.
Same results and no luck.

**Comment by EricMaeker** [comment]
This is a simple checking I have done :
- download latest Dokuwiki (without any plugin)
- install pubmed freshly downloaded from github
- create start from the dokuwiki UI
- added {{pubmed>vancouver:30644303}}
- result :
Chompoosang T, D'Apolito R, Lacagnina C, Peretti G, Zagra L. Total hip
arthroplasty in rapidly progressive osteoarthritis of the hip: clinical and
radiological outcome of a consecutive series of patients. J Biol Regul
Homeost Agents. 2018 Nov-Dec;32(6 Suppl. 1):201-207

Do you have any error from your server ? Did you purge your cache ?

**Comment by cbso-uc** [comment]
I'd followed [dokuwiki's instructions](https://www.dokuwiki.org/faq:pluginproblems) to purge cache and tried with different browsers.

I will try to disable other plugins and try again.

**Comment by EricMaeker** [comment]
Did you check user owner of the media/ncbi_esummary dir ?
Use `ls -al`
There should be four files : all your three pubmed_PMDI.xml.gz and
crossref.xml.gz

**Comment by EricMaeker** [comment]
Can you send the full code of your page ?

**Comment by cbso-uc** [comment]
ls -la data/media/ncbi_esummary is totally empty
`total 8
drwxrwxr-x 2 www-data www-data 4096 Jan  6  2019 .
drwxrwsr-x 6 bso      www-data 4096 Oct 27 09:59 ..`

`====== Rapidly Progressive Osteoarthritis (RPOA) ======

  - Distinct from Primary OA by features and progression (({{pubmed>long:28328832}}))
    - older female more common {{pubmed>30644303}}
    - less ROM limitation compared with primary OA
    - pain onset average 3 years vs 5 years
    - 9.5% of a series of 863 patients who undergone THR (Primary OA 52.8%)
    - may be distinct from Primary OA
    - most commonly the hips but can occur in the shoulders
  - Two Stages (({{pubmed>long:28689367}}))
    - Early Chondrolysis Stage
      * MRI
        - bone edema
        - subchondral fracture
    - Late-Subchondral Destruction Stage
  - Two grading systems
    - Type 1-2 : no collapse vs collapse
    - Grades 1-3
      - Grade 1 - jt space narrowed
      - Grade 2 - deformed femoral head with <= 5mm ascension above teardrop
      - Grade 3 - complete loss of jt space, osteolysis,  > 5mm ascension
{{ :msk:rpoa_grades.jpg?400 |}}
  - Distinct feature vs Primary OA
    - presences of geodes at all stages
    - osteophytes absent or not prominent
    - absence of a demarcation between healthy and necrotic tissue cf. AVN
  - corticosteroid injection - less likely to be effective to manage pain in advanced stages
  - Definitive treatment - THR
  - Added surgical difficulties - opinion varies
    - intra and postoperative blood loss was similar in one series but higher blood loss reported in another series
    - immediate postop complication - not significant
    - prosthesis take and complications concerns raised - no hard evidence as far as reported (({{pubmed>long:30644303}}))

===== References =====

~~NOCACHE~~`

**Comment by EricMaeker** [comment]
Absolutely no problem here with this wiki code !

What is the output of
ls -la data/*

and
ls -la data/media/*

**Comment by EricMaeker** [comment]
Did you set a different path in the config file of your site for the pubmed
plugin ?

>

**Comment by cbso-uc** [comment]
tried disabling all plugins except farmer and pubmed, still no luck.

bso@R3SSD:/var/www/dokuwiki $ ls -la data/
total 96
drwxrwsr-x 12 bso www-data  4096 Jan  6  2019 .
drwxrws---  8 bso www-data  4096 Jan  6  2019 ..
drwxrwsr-x  2 bso www-data  4096 Jan  6  2019 attic
drwxrwsr-x 17 bso www-data  4096 Oct 27 10:49 cache
-rwxrwsr-x  1 bso www-data 19724 Jan  6  2019 deleted.files
-rwxrwsr-x  1 bso www-data  6516 Jan  6  2019 dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png
-rwxrwsr-x  1 bso www-data 12093 Jan  6  2019 dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.xcf
-rwxrwsr-x  1 bso www-data    32 Jan  6  2019 _dummy
-rwxrwsr-x  1 bso www-data   139 Jan  6  2019 .htaccess
drwxrwsr-x  2 bso www-data  4096 Jan  6  2019 index
drwxrwsr-x  2 bso www-data  4096 Oct 27 10:58 locks
drwxrwsr-x  6 bso www-data  4096 Oct 27 09:59 media
drwxrwsr-x  2 bso www-data  4096 Jan  6  2019 media_attic
drwxrwsr-x  2 bso www-data  4096 Jan  6  2019 media_meta
drwxrwsr-x  4 bso www-data  4096 Mar 17  2019 meta
drwxrwsr-x  4 bso www-data  4096 Jan  6  2019 pages
drwxrwsr-x  2 bso www-data  4096 Oct 26 19:08 tmp
bso@R3SSD:/var/www/dokuwiki $ ls -la data/media
total 24
drwxrwsr-x  6 bso      www-data 4096 Oct 27 09:59 .
drwxrwsr-x 12 bso      www-data 4096 Jan  6  2019 ..
drwxrwxr-x  2 www-data www-data 4096 Jan  6  2019 ncbi_esummary
drwxrwxr-x  2 www-data www-data 4096 Oct 27 09:59 ncbi_esummary_doi_pdf
drwxrwxr-x  2 www-data www-data 4096 Oct 27 09:59 ncbi_esummary_pmid_pdf
drwxrwsr-x  2 bso      www-data 4096 Jan  6  2019 wiki

**Comment by cbso-uc** [comment]
bso@R3SSD:/var/www/dokuwiki $ ls -la lib/plugins/pubmed/conf
total 16
drwxrws--- 2 www-data www-data 4096 Oct 27 09:28 .
drwxr-sr-x 7 www-data www-data 4096 Oct 27 09:28 ..
-rwxrwx--- 1 www-data www-data  314 Oct 27 09:28 default.php
-rwxrwx--- 1 www-data www-data  509 Oct 27 09:28 metadata.php

**Comment by EricMaeker** [comment]
Try in dokuwiki path

sudo chown bso:www-data -R *

And if this does not correct the plugin functions, please have a look at
your server log file and php log file. Check any error found.

>

**Comment by cbso-uc** [comment]
Apache2 error.log

[Sun Oct 27 11:23:56.818193 2019] [php7:warn] [pid 20055] [client 184.64.172.33:12222] PHP Warning:  Declaration of syntax_plugin_pubmed::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/dokuwiki/lib/plugins/pubmed/syntax.php on line 14
[Sun Oct 27 11:23:56.818340 2019] [php7:warn] [pid 20055] [client 184.64.172.33:12222] PHP Warning:  Declaration of syntax_plugin_pubmed::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /var/www/dokuwiki/lib/plugins/pubmed/syntax.php on line 14

**Comment by EricMaeker** [comment]
What is your PHP version ?

  Éric

**Comment by cbso-uc** [comment]
PHP7.3

**Comment by EricMaeker** [comment]
Ah ok, give me few hours to test with PHP 7.3 please.

**Comment by EricMaeker** [comment]
What is the version of dokuwiki ?

**Comment by EricMaeker** [comment]
Can you update the pubmed plugin, I've just pushed new code and test please
?

**Comment by cbso-uc** [comment]
2018-04-22b "Greebo"

manually reinstalled plugin from your updated files in GitHub. Still the same issue.
there are no files in data/media/ncbi_esummary

Sorry to have taken up your evening.

**Comment by EricMaeker** [comment]
No problem. Can you send the new php error please.

**Comment by EricMaeker** [comment]
Ok code updated. Seems ok with PHP7. Can you update and test please

**Comment by cbso-uc** [comment]
Updated, checked permissions and cleared cache. Re-saved dokuwiki configuration. Restarted apache2.
No luck.
Checked error.log - no longer flag previous error. No new error item in log.

**Comment by EricMaeker** [comment]
Mmmm. Do you have apache errors ?

**Comment by cbso-uc** [comment]
Nothing suggestive in the Apache log. Could be a configuration issue but too hard for me to figure out. I will revert to Ikuo Obataya’s more basic version of the plugin for now.
Thanks for taking the time to look into this.

**Comment by EricMaeker** [comment]
Ok i will make some tests on debian10 and send back a small report asap.

>

**Comment by EricMaeker** [comment]
Ok Test done :
- Freshly installed Debian10 desktop gnome
- Installed Apache2
- Installed PHP7 + PHP extensions
- Nothing more
- Dokuwiki freshly downloaded from the dokuwiki site
- Pubmed plugin freshly downloaded from the github
- Testing {{pubmed>vancouver:30644303}}

Perfect result without any error... Please check your configuration.
I can help you to find what is wrong on your server

**Comment by EricMaeker** [comment]
Also done a chmod 777 -R * at dokuwiki root before running dokuwiki
install.php

**Comment by cbso-uc** [comment]
I have also done a similar test with a minimal os install and ran into the same issues which leads me to think Debian on the Raspberry Pi (Raspbian) seems to be responsible.

Observations:
- Can only get {{pubmed>search:PMID}} and  {{pubmed>summaryxml:PMID}} to show.
- Other commands actually blanks the whole page, i.e., other contents became invisible.
- The content of the with {{pubmed>summaryxml:PMID}} is also different from Ikuo Obataya’s version. His version shows all the xml tags but yours do not (see my screenshot from my post 2 days ago above).

The steps were as follows :
- reformatted SD card
- downloaded latest Raspbian Buster for Raspberry Pi (lite version to run headless)
- copied to SD card and install in Raspberry Pi and installed os via remote web browser
- only ran sudo apt update and then installed apache2 and php
- downloaded latest stable version of dokuwiki and extracted into /var/www/html/
- chmod 777 -R on dokuwiki
- downloaded your pubmed files and placed in dokuwiki's plugin directory
- chown to www-data:www-data
- chmod 777 -R on the pubmed folder
- remote web browser access to dokuwiki on the raspberry pi
- created new page with minimal content and tested

**Comment by cbso-uc** [comment]
May be you can figure out what is wrong from the phpinfo() output attached.

[PHP 7.3.11-1_deb10u1 - phpinfo().pdf](https://github.com/EricMaeker/dokuwiki-plugin-pubmed/files/3786710/PHP.7.3.11-1_deb10u1.-.phpinfo.pdf)

**Comment by EricMaeker** [comment]
Thanks for this report. Did you install PHP extensions ?

sudo apt-get install -y php7.3-dom php7.3-simplexml php7.3-ssh2
php7.3-xml php7.3-xmlreader php7.3-curl  php7.3-exif  php7.3-ftp
php7.3-gd  php7.3-iconv php7.3-imagick php7.3-json  php7.3-mbstring
php7.3-posix php7.3-sockets php7.3-tokenizer

**Comment by EricMaeker** [comment]
Also summaryxml bug corrected and commited

>

**Comment by cbso-uc** [comment]
Thanks for the pointers. Finally worked out where the problem is: need to install php-xml

After reinstalling Raspbian several times and testing PHP extensions one at a time, narrowed down to php-xml.

For anyone using Raspbian on a Raspberry Pi as a webserver, these are the steps from a basic install starting from scratch (substitute dokuwiki version as applicable):

sudo apt update; sudo apt install apache2 -y
sudo apt install php libapache2-mod-php -y
sudo apt install php-xml -y
sudo systemctl restart apache2
cd /var/www/html
sudo wget https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
sudo tar xzf dokuwiki-stable.tgz
sudo mv dokuwiki-2018-04-22b dokuwiki
sudo chown www-data:www-data -R dokuwiki
sudo chmod 2775 -R dokuwiki
cd dokuwiki/lib/plugins/

now download the current pubmed plugin files from GitHub and place in the plugins folder. Make sure they are in a directory named pubmed. Then change ownership and permission

sudo chown www-data:www-data -R pubmed
sudo chmod 2775 -R pubmed

Goto your webbrowser and connect to dokuwiki to finish installation:
http://your-server.ip.address/dokuwiki/install.php

To test pubmed plugin, create a new page with the following markup:
====== PlayGround ======
{{pubmed>clear_summary:28328832}}
{{pubmed>long:28328832}}

**Comment by cbso-uc** [comment]
![Pubmed_Success](https://user-images.githubusercontent.com/57051636/67896482-0ef66780-fb22-11e9-915e-0a4bc80d5130.JPG)

**Comment by EricMaeker** [comment]
Yes only one extension is necessary. php-xml
Thanks for your report and documentation
I will add a notice in the readme file
